import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import Sidebar from "./components/Sidebar";
import Providers from "./redux/Providers";
import SessionProviders from "./components/SessionProviders";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProviders>
          <Providers>
            <div className="flex">
              <Sidebar />
              <main className="flex-1 p-3">{children}</main>
            </div>
          </Providers>
        </SessionProviders>
      </body>
    </html>
  );
}
